name: Erlang CI

on:
  push:
    branches: [ "AI2001_Category-Source_Code-SC-Erlang_Main-dev" ]
  pull_request:
    branches: [ "AI2001_Category-Source_Code-SC-Erlang_Main-dev" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.0.7

    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 do eunit, ct
